### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by TerAnYu** [akafeng/docker-bird#1]
**docker-compose.yml**
```
version: '3'
services:
  bird2:
    image: ghcr.io/akafeng/bird:latest
    container_name: bird2
    hostname: "bird2"
    restart: always
#    volumes:
#      - ./etc:/etc/bird
    ports:  
      - 179:179/tcp  # tcp bgp
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
```

Thanks for your image and Dockerfile !

It's a pity that if you do
```
    volumes:
      - ./etc:/etc/bird
```
then the container cannot start because the **bird.conf** file is missing, which itself is not created :(
